#!/bin/bash
#
# Add gitolite user (with no permissions to any repo). 
#
# $1 = name of repo
# $2 = folder of repo files
#
. $(dirname $0)/_helper_gitolite      #import functions
. $(dirname $0)/_helper_gitolite_repo #import functions
repo=$1 
repopath=$2 

echo "====repo = $repo"
echo "====repopath = $repopath"

#check if we have git user name (i.e. config file)
git_check_user_name
#get git user name
git_user=$(get_git_user_name)
git_user_admin="$git_user-admin"
git_user_admin_home=$(eval echo "~$git_user_admin")
path="$git_user_admin_home/gitolite-admin/conf/gitolite.conf"

cfg=$(gitolite_add_repo $repo $repopath $path)

if [[ "$cfg" == ERR* ]]; then
	if [ "$cfg" == "ERR_PARAMS" ]; then printf "\n\n\tUsage: $0 gitolite grant <repo> <user> <perm>\n\n"; exit -1; fi
	if [ "$cfg" == "ERR_NO_FILE" ]; then echo "ERROR: Cannot find gitolite config file"; exit -1; fi
	if [ "$cfg" == "ERR_NO_FOLDER" ]; then echo "ERROR: Cannot find repo folder"; exit -1; fi
	if [ "$cfg" == "ERR_ADMIN_REPO" ]; then echo "ERROR: Cannot change admin user perms (please do not shoot yourself in the feet)"; exit -1; fi
	#fallback error message
	echo "$cfg"; exit -1;
fi

echo "$cfg"
#echo "$cfg" > "$path"
#chown "$git_user_admin":"$git_user_admin" "$path"

#gitolite_save "add repo $repo"