#!/bin/bash
#
# Add gitolite user (with no permissions to any repo). 
#
# $1 = name of user
# $2 = path to public key of user.
#
. $(dirname $0)/_helper          #import functions
. $(dirname $0)/_helper_gitolite #import functions

user=$1 
keypath=$2 

#check input params
if [ -z $user ] || [ -z $keypath ]; then printf "\n  Usage: $0 gitolite add user <name> <keypath>\n\n"; exit -1; fi
if [ ! -e $keypath ]; then echo "ERROR: file '$keypath' does not exists"; exit; fi
ssh-keygen -l -f $keypath > /dev/null
if [ ! $? -eq 0 ]; then echo "ERROR: file '$keypath' is not a public key file"; exit; fi

#get git user name
git_user=$(get_git_user_name)
git_user_admin="$git_user-admin"
git_user_admin_home_dir=$(eval echo "~$git_user_admin")

#check if we have git user name (i.e. config file)
git_check_user_name

#check if user unique
users=$(ls "$git_user_admin_home_dir/gitolite-admin/keydir/")
users=${users//\.pub/}
if [[ $users == *$user* ]]; then echo "ERROR: User '$user' already exists"; exit -1; fi

#copy keyfile to gitolite
cp "$keypath" "$git_user_admin_home_dir/gitolite-admin/keydir/$user.pub"
#ajust rights
chown "$git_user_admin":"$git_user_admin" "$git_user_admin_home_dir/gitolite-admin/keydir/$user.pub"

gitolite_save "add user $user"
